# Generated by Django 4.2.7 on 2024-01-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='spec',
        ),
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
