# Generated by Django 4.2.6 on 2024-01-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_phone_spec_phone_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone',
            new_name='Phonemodel',
        ),
    ]
