# Generated by Django 4.2.6 on 2024-01-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_phone_phonemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='brand',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='price',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
